# Generated by Django 3.0.1 on 2020-01-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorMatching', '0003_auto_20191224_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='students',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='available',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='subscribed',
        ),
        migrations.AddField(
            model_name='courses',
            name='course_dept',
            field=models.CharField(default='def', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='course_title',
            field=models.CharField(default='def', max_length=100),
            preserve_default=False,
        ),
    ]
