# Generated by Django 3.0.1 on 2020-01-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorMatching', '0004_auto_20200108_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='course_num',
            field=models.IntegerField(default=100, max_length=3),
            preserve_default=False,
        ),
    ]
