# Generated by Django 3.0.2 on 2020-02-13 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorMatching', '0008_auto_20200108_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutors',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
