export const ADD_MATCH_STUDENT_SUCCESS = "ADD_MATCH_STUDENT_SUCCESS";
export const ADD_MATCH_STUDENT_FAIL = "ADD_MATCH_STUDENT_FAIL";

export const ADD_MATCH_TUTOR_SUCCESS = "ADD_MATCH_TUTOR_SUCCESS";
export const ADD_MATCH_TUTOR_FAIL = "ADD_MATCH_TUTOR_FAIL";

export const GET_STUDENTS_SUCCESS = "GET_STUDENTS_SUCCESS";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_FAIL = "ADD_STUDENT_FAIL";
export const REMOVE_STUDENT_SUCCESS = "REMOVE_STUDENT_SUCCESS";
export const REMOVE_STUDENT_FAIL = "REMOVE_STUDENT_FAIL";

export const GET_TUTORS_SUCCESS = "GET_TUTORS_SUCCESS";
export const ADD_TUTOR_SUCCESS = "ADD_TUTOR_SUCCESS";
export const ADD_TUTOR_FAIL = "ADD_TUTOR_FAILED";
export const UPDATE_TUTOR_PRICE_SUCCESS = "UPDATE_TUTOR_PRICE_SUCCESS";
export const UPDATE_TUTOR_PRICE_FAIL = "UPDATE_TUTOR_PRICE_SUCCESS";
export const REMOVE_TUTOR_SUCCESS = "REMOVE_TUTOR_SUCCESS";
export const REMOVE_TUTOR_FAIL = "REMOVE_TUTOR_FAIL";

export const GET_COURSES_SUCCESS = "GET_COURSES_SUCCESS";

export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";

export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const GET_ERRORS = "GET_ERRORS";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAIL = "LOGOUT_FAIL";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const PASS_REQUEST_SUCCESS = "PASS_REQUEST_SUCCESS";
export const PASS_REQUEST_FAILED = "PASS_REQUEST_FAILED";

export const VERIFY_ACCOUNT_SUCCESS = "VERIFY_ACCOUNT_SUCCESS";
export const VERIFY_ACCOUNT_FAILED = "VERIFY_ACCOUNT_FAILED";

export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILED = "RESET_PASSWORD_FAILED";

export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";